In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn
import os
import json
from tqdm.notebook import tqdm

import sklearn
from sklearn.preprocessing import LabelEncoder
from sklearn.cluster import KMeans

In [16]:
with open('config/config.json', 'r') as file:
    config = json.load(file)

# Loading Data

In [17]:
df = pd.read_csv(config['ticker_data_close'], index_col=0)
df_index = pd.read_csv(config['ticker_data_sp500'], index_col=0)
df.head()

,SPGI,MCO,CPRT,EFX,FLT,CRL,OMC,IPG,RHI,NLSN,...,ETR,CMS,CNP,AES,EVRG,LNT,ATO,NI,NRG,PNW
Date,,,,,,,,,,,,,,,,,,,,,
2018-01-02,168.119995,146.130005,43.599998,119.540001,193.869995,110.650002,72.769997,20.250000,55.910000,36.660000,...,82.599998,46.950001,28.020000,10.88,53.139999,42.110001,85.040001,25.360001,28.900000,83.889999
2018-01-03,170.820007,148.860001,43.389999,120.160004,194.960007,110.309998,70.360001,19.760000,55.810001,35.990002,...,81.690002,46.660000,27.959999,10.87,52.320000,41.740002,84.339996,25.200001,28.879999,83.120003
2018-01-04,173.380005,151.600006,43.740002,121.639999,195.460007,109.470001,71.059998,20.170000,55.980000,35.790001,...,80.540001,46.139999,27.990000,10.83,52.099998,41.250000,83.980003,25.090000,28.549999,82.510002
2018-01-05,175.699997,154.119995,43.529999,122.830002,197.000000,111.879997,72.169998,20.190001,56.310001,36.000000,...,79.919998,45.810001,27.870001,10.87,51.660000,41.080002,83.190002,24.790001,28.730000,82.419998
2018-01-08,177.179993,155.070007,43.549999,121.989998,197.160004,111.889999,72.410004,20.350000,56.770000,36.160000,...,80.839996,46.340000,28.040001,10.87,51.720001,41.540001,83.449997,25.000000,29.170000,83.050003

In [18]:
df_na = df.isna().sum() 
stocks_to_drop = df_na[df_na > 0].index.tolist()
df = df.drop(stocks_to_drop, axis=1)

In [19]:
df_for_metrics = df.pct_change()[1:]

In [20]:
df_for_metrics.head()

,SPGI,MCO,CPRT,EFX,FLT,CRL,OMC,IPG,RHI,NLSN,...,ETR,CMS,CNP,AES,EVRG,LNT,ATO,NI,NRG,PNW
Date,,,,,,,,,,,,,,,,,,,,,
2018-01-03,0.016060,0.018682,-0.004816,0.005187,0.005622,-0.003073,-0.033118,-0.024198,-0.001789,-0.018276,...,-0.011017,-0.006177,-0.002141,-0.000919,-0.015431,-0.008786,-0.008231,-0.006309,-0.000692,-0.009179
2018-01-04,0.014987,0.018407,0.008066,0.012317,0.002565,-0.007615,0.009949,0.020749,0.003046,-0.005557,...,-0.014078,-0.011144,0.001073,-0.003680,-0.004205,-0.011739,-0.004268,-0.004365,-0.011427,-0.007339
2018-01-05,0.013381,0.016623,-0.004801,0.009783,0.007879,0.022015,0.015621,0.000992,0.005895,0.005868,...,-0.007698,-0.007152,-0.004287,0.003693,-0.008445,-0.004121,-0.009407,-0.011957,0.006305,-0.001091
2018-01-08,0.008423,0.006164,0.000459,-0.006839,0.000812,0.000089,0.003326,0.007925,0.008169,0.004444,...,0.011511,0.011569,0.006100,0.000000,0.001161,0.011198,0.003125,0.008471,0.015315,0.007644
2018-01-09,0.000339,0.006771,-0.001607,0.002131,-0.001268,-0.012691,-0.004557,-0.001966,-0.002466,0.004701,...,-0.008906,-0.013595,-0.009986,-0.010120,0.010247,-0.015166,-0.010306,-0.012000,-0.015427,-0.012402

In [32]:
list(df_for_metrics.columns)

['SPGI',
 'MCO',
 'CPRT',
 'EFX',
 'FLT',
 'CRL',
 'OMC',
 'IPG',
 'RHI',
 'NLSN',
 'VZ',
 'T',
 'TMUS',
 'LUMN',
 'TSLA',
 'GM',
 'F',
 'ATVI',
 'EA',
 'DHI',
 'SWK',
 'TTWO',
 'NVR',
 'LKQ',
 'PHM',
 'WHR',
 'HAS',
 'MHK',
 'SNA',
 'PG',
 'NKE',
 'KO',
 'PEP',
 'PM',
 'EL',
 'MDLZ',
 'MO',
 'CL',
 'MNST',
 'KMB',
 'STZ',
 'KHC',
 'GIS',
 'HSY',
 'IFF',
 'TSN',
 'VFC',
 'HRL',
 'MKC',
 'CHD',
 'K',
 'CLX',
 'CAG',
 'SJM',
 'CPB',
 'TAP',
 'LW',
 'UAA',
 'UA',
 'PVH',
 'DIS',
 'CMCSA',
 'MCD',
 'SBUX',
 'CHTR',
 'BKNG',
 'MAR',
 'CMG',
 'CTAS',
 'HLT',
 'YUM',
 'LVS',
 'EXPE',
 'LYV',
 'MGM',
 'VIAC',
 'RCL',
 'DPZ',
 'CZR',
 'DRI',
 'DISH',
 'ROL',
 'NWSA',
 'NWS',
 'DISCA',
 'DISCK',
 'WYNN',
 'NCLH',
 'PENN',
 'SYY',
 'MCK',
 'FAST',
 'ABC',
 'GWW',
 'POOL',
 'GPC',
 'CAH',
 'HSIC',
 'AAPL',
 'NVDA',
 'AVGO',
 'INTC',
 'QCOM',
 'AMD',
 'TXN',
 'RTX',
 'BA',
 'MU',
 'LRCX',
 'LMT',
 'ADI',
 'KLAC',
 'NXPI',
 'NOC',
 'GD',
 'XLNX',
 'FTNT',
 'TEL',
 'APH',
 'MCHP',
 'MSI',
 'ANET',
 'LHX',
 'HPQ',
 'KEYS',
 'TDG',
 'GLW',
 'ZBRA',
 'TER',
 'SWKS',
 'FTV',
 'GRMN',
 'STX',
 'ENPH',
 'MPWR',
 'TRMB',
 'HPE',
 'TDY',
 'WDC',
 'NTAP',
 'QRVO',
 'TXT',
 'FFIV',
 'HWM',
 'IPGP',
 'HII',
 'XOM',
 'CVX',
 'COP',
 'EOG',
 'PXD',
 'MPC',
 'PSX',
 'VLO',
 'DVN',
 'OXY',
 'HES',
 'FANG',
 'CTRA',
 'MRO',
 'APA',
 'JPM',
 'V',
 'BAC',
 'MA',
 'WFC',
 'MS',
 'SCHW',
 'BLK',
 'AMT',
 'GS',
 'AXP',
 'PLD',
 'C',
 'CCI',
 'PNC',
 'USB',
 'MMC',
 'CB',
 'CME',
 'EQIX',
 'ICE',
 'PSA',
 'AON',
 'COF',
 'PGR',
 'MET',
 'SPG',
 'DLR',
 'BK',
 'AIG',
 'TROW',
 'SBAC',
 'PRU',
 'O',
 'SIVB',
 'AFL',
 'TRV',
 'WELL',
 'CBRE',
 'AVB',
 'FRC',
 'DFS',
 'AJG',
 'ARE',
 'STT',
 'AMP',
 'EQR',
 'ALL',
 'NDAQ',
 'WY',
 'FITB',
 'EXR',
 'WLTW',
 'MAA',
 'SYF',
 'DRE',
 'NTRS',
 'URI',
 'HIG',
 'ESS',
 'RF',
 'RJF',
 'VTR',
 'CFG',
 'MTB',
 'PEAK',
 'BRO',
 'PFG',
 'SBNY',
 'UDR',
 'CINF',
 'BXP',
 'BEN',
 'KIM',
 'IRM',
 'MKTX',
 'L',
 'WRB',
 'CBOE',
 'REG',
 'LNC',
 'HST',
 'CMA',
 'IVZ',
 'RE',
 'FRT',
 'ZION',
 'GL',
 'AIZ',
 'VNO',
 'PBCT',
 'UNH',
 'ANTM',
 'HCA',
 'CI',
 'HUM',
 'IQV',
 'CNC',
 'LH',
 'DGX',
 'DVA',
 'UHS',
 'JNJ',
 'PFE',
 'LLY',
 'TMO',
 'ABT',
 'ABBV',
 'DHR',
 'MRK',
 'MDT',
 'BMY',
 'ISRG',
 'AMGN',
 'ZTS',
 'SYK',
 'GILD',
 'EW',
 'BDX',
 'REGN',
 'BSX',
 'ILMN',
 'VRTX',
 'IDXX',
 'ALGN',
 'DXCM',
 'A',
 'BAX',
 'MTD',
 'RMD',
 'BIIB',
 'WST',
 'ZBH',
 'STE',
 'PKI',
 'WAT',
 'BIO',
 'CTLT',
 'COO',
 'TECH',
 'HOLX',
 'VTRS',
 'ABMD',
 'INCY',
 'TFX',
 'XRAY',
 'WM',
 'SLB',
 'RSG',
 'KMI',
 'WMB',
 'OKE',
 'BKR',
 'HAL',
 'J',
 'PWR',
 'FCX',
 'NEM',
 'NUE',
 'VMC',
 'MLM',
 'LIN',
 'SHW',
 'ECL',
 'APD',
 'DD',
 'PPG',
 'ADM',
 'LYB',
 'BLL',
 'ALB',
 'CE',
 'AMCR',
 'IP',
 'AVY',
 'EMN',
 'MOS',
 'CF',
 'FMC',
 'PKG',
 'WRK',
 'SEE',
 'HON',
 'AMAT',
 'CAT',
 'DE',
 'GE',
 'MMM',
 'ITW',
 'ETN',
 'JCI',
 'EMR',
 'TT',
 'APTV',
 'PH',
 'ROK',
 'AME',
 'CMI',
 'PCAR',
 'DOV',
 'IR',
 'GNRC',
 'XYL',
 'IEX',
 'WAB',
 'MAS',
 'SEDG',
 'FBHS',
 'AOS',
 'PNR',
 'ALLE',
 'BWA',
 'NWL',
 'AMZN',
 'HD',
 'WMT',
 'COST',
 'LOW',
 'CVS',
 'TGT',
 'TJX',
 'DG',
 'ORLY',
 'WBA',
 'AZO',
 'EBAY',
 'ROST',
 'KR',
 'DLTR',
 'TSCO',
 'ETSY',
 'BBY',
 'ULTA',
 'KMX',
 'BBWI',
 'AAP',
 'TPR',
 'RL',
 'GPS',
 'MSFT',
 'GOOG',
 'GOOGL',
 'FB',
 'ACN',
 'CSCO',
 'NFLX',
 'CRM',
 'ORCL',
 'PYPL',
 'INTU',
 'NOW',
 'IBM',
 'ADP',
 'FISV',
 'FIS',
 'ADSK',
 'SNPS',
 'INFO',
 'CDNS',
 'ROP',
 'MSCI',
 'PAYX',
 'CTSH',
 'GPN',
 'MTCH',
 'EPAM',
 'VRSK',
 'ANSS',
 'TWTR',
 'VRSN',
 'CDW',
 'CERN',
 'IT',
 'PAYC',
 'TYL',
 'BR',
 'AKAM',
 'FDS',
 'NLOK',
 'PTC',
 'JKHY',
 'LDOS',
 'CTXS',
 'JNPR',
 'DXC',
 'UPS',
 'UNP',
 'CSX',
 'FDX',
 'ODFL',
 'LUV',
 'DAL',
 'EXPD',
 'JBHT',
 'UAL',
 'CHRW',
 'AAL',
 'ALK',
 'NEE',
 'DUK',
 'SO',
 'D',
 'EXC',
 'AEP',
 'SRE',
 'XEL',
 'PEG',
 'AWK',
 'ES',
 'WEC',
 'ED',
 'EIX',
 'DTE',
 'AEE',
 'PPL',
 'FE',
 'ETR',
 'CMS',
 'CNP',
 'AES',
 'EVRG',
 'LNT',
 'ATO',
 'NI',
 'NRG',
 'PNW']

# Calculating features

1. средняя доходность
2. стандартное отклонение
3. просадки (хотя бы максимальная за период)
4. период восстановления
5. beta
6. Alfa
7. Sharp
8. VaR
9. CAPM
10. IR
11. Пересечение длинной и короткой SMA (тут нужно строить две линии SMA за разные периоды и смотреть когда они пересекаются
12. Ликвидность (формула = (Q*V)/T, где Q - количество сделок, V - средний объем сделок, T - время, за которое эти сделки были совершены),
13. Coef of variation

In [ ]:
def find_max_recovery(prices):
    """
    Takes Series with closing prices.
    Returns the value of maximum recovery
    period in days and indexes of prices
    where this recovery period took place.
    """
    growth = calc_growth(prices)
    s = 0
    left = 0
    right = 0
    curr_left = 0
    max_recovery = 0
    for i in range(0, len(growth)):
        if not s:
            curr_left = i
        s += growth[i]
        if s > 0:
          s = 0
          if max_recovery < (i - curr_left):
              max_recovery = i - curr_left
              left = curr_left
              right = i
            
    return max_recovery, left, right + 1

In [ ]:
def find_max_drawdown(prices):
    """
    Takes Series with closing prices.
    Returns the value of maximum drawdown
    in percent and indexes of prices where this
    maximum drawdown took place. If stock is
    always growing it will return minimum
    growth with and indexes of prices where this
    minimum growth took place.
    """
    max_price = prices.iloc[0]
    curr_drawdown = 0
    max_drawdown = 0
    curr_left = 0
    left = 0
    right = 0
    for i in range(0, len(prices)):
        curr_drawdown = (prices.iloc[i] / max_price - 1) * 100
        if curr_drawdown < max_drawdown:
            max_drawdown = curr_drawdown
            left = curr_left
            right = i
        if prices.iloc[i] > max_price:
            max_price = prices.iloc[i]
            curr_left = i
    return max_drawdown, left, right

In [ ]:
#расчет беты, корреляции, alfa, VAR,

def beta_cal(df_pct):
  return (df_pct.cov()['market'] / df_pct.var()['market'])

def cor_cal(df_pct):
  return df_pct.drop(['market'], axis = 1).corr()

def alfa_cal(df_pct):
  return df_pct.drop(['market'], axis = 1) - beta_cal(df_pct) * df_pct['market']

def VaR_cal(df_pct, alpha=5):  #historical
#Output the percentile of the distribution at the given alpha confidence level
  return df_pct.drop(['market'], axis = 1).quantile(0.05)

def CVaR_cal(df_pct, alpha=5):
  belowVaR = df_pct.drop(['market'], axis = 1) <= VaR_cal(df_pct, alpha = alpha)
  return df_pct[belowVaR].mean()

# Preprocessing

In [5]:
df = df.pct_change()[1:]
df = df.T
df.head()

Date,2018-01-03,2018-01-04,2018-01-05,2018-01-08,2018-01-09,2018-01-10,2018-01-11,2018-01-12,2018-01-16,2018-01-17,...,2022-01-19,2022-01-20,2022-01-21,2022-01-24,2022-01-25,2022-01-26,2022-01-27,2022-01-28,2022-01-31,2022-02-01
SPGI,0.016060,0.014987,0.013381,0.008423,0.000339,-0.009197,0.004499,0.007030,-0.010189,0.005460,...,-0.002829,-0.011751,-0.002512,0.002447,-0.044072,-0.004981,-0.006188,0.029209,0.021150,0.005395
MCO,0.018682,0.018407,0.016623,0.006164,0.006771,-0.008391,0.005878,0.009825,-0.010938,0.012088,...,0.006417,-0.003924,-0.009847,0.006464,-0.055365,-0.001508,0.004252,0.032493,0.019286,0.002624
CPRT,-0.004816,0.008066,-0.004801,0.000459,-0.001607,0.000920,0.022518,0.007865,-0.011817,0.000226,...,-0.007823,-0.026535,-0.013318,0.021549,-0.018003,-0.030687,-0.013637,0.032178,0.030537,0.001393
EFX,0.005187,0.012317,0.009783,-0.006839,0.002131,-0.008753,0.002558,0.011194,-0.005617,0.008677,...,-0.028006,-0.022529,-0.013077,0.037800,-0.034715,0.002433,-0.007458,0.040592,0.024396,0.010260
FLT,0.005622,0.002565,0.007879,0.000812,-0.001268,0.020314,0.008312,0.003406,-0.007232,0.007929,...,-0.002687,-0.016794,-0.030738,-0.004240,0.001419,-0.008726,-0.003173,0.036846,0.030046,0.010199

# Feature engineering

In [6]:
df_sectors = pd.read_csv(config['tickers_sectors_path'], index_col=0)
df_sectors.head()

  ticker       sector
0   SPGI    Financial
1    MCO    Financial
2   CPRT  Industrials
3    EFX  Industrials
4    FLT   Technology

In [9]:
dict_tick_sect = dict(zip(df_sectors['ticker'].values.tolist(),
                         df_sectors['sector'].values.tolist()))

df['sector'] = df.index.map(dict_tick_sect)
df.head()

Date,2018-01-03,2018-01-04,2018-01-05,2018-01-08,2018-01-09,2018-01-10,2018-01-11,2018-01-12,2018-01-16,2018-01-17,...,2022-01-20,2022-01-21,2022-01-24,2022-01-25,2022-01-26,2022-01-27,2022-01-28,2022-01-31,2022-02-01,sector
SPGI,0.016060,0.014987,0.013381,0.008423,0.000339,-0.009197,0.004499,0.007030,-0.010189,0.005460,...,-0.011751,-0.002512,0.002447,-0.044072,-0.004981,-0.006188,0.029209,0.021150,0.005395,Financial
MCO,0.018682,0.018407,0.016623,0.006164,0.006771,-0.008391,0.005878,0.009825,-0.010938,0.012088,...,-0.003924,-0.009847,0.006464,-0.055365,-0.001508,0.004252,0.032493,0.019286,0.002624,Financial
CPRT,-0.004816,0.008066,-0.004801,0.000459,-0.001607,0.000920,0.022518,0.007865,-0.011817,0.000226,...,-0.026535,-0.013318,0.021549,-0.018003,-0.030687,-0.013637,0.032178,0.030537,0.001393,Industrials
EFX,0.005187,0.012317,0.009783,-0.006839,0.002131,-0.008753,0.002558,0.011194,-0.005617,0.008677,...,-0.022529,-0.013077,0.037800,-0.034715,0.002433,-0.007458,0.040592,0.024396,0.010260,Industrials
FLT,0.005622,0.002565,0.007879,0.000812,-0.001268,0.020314,0.008312,0.003406,-0.007232,0.007929,...,-0.016794,-0.030738,-0.004240,0.001419,-0.008726,-0.003173,0.036846,0.030046,0.010199,Technology

# Clustering

In [10]:
n_clusters_ = df_sectors['sector'].nunique()

df_predictions = pd.DataFrame(df['sector'].values, index=df.index, columns=['original'])
df_predictions['original_n'] = LabelEncoder().fit_transform(df_predictions['original'])

dict_features = dict()

df_predictions

TypeError: argument must be a string or number

In [11]:
model_name = 'Original'

X = df.drop(['sector'], axis=1).values
dict_features[model_name] = X

clust_pred = df_predictions['original_n']
df_predictions[model_name] = clust_pred

NameError: name 'dict_features' is not defined

In [84]:
model_name = 'Kmeans_original'

X = df.drop(['sector'], axis=1).values
dict_features[model_name] = X

kmeans = KMeans(n_clusters=n_clusters_, random_state=0).fit(X)
clust_pred = kmeans.labels_
df_predictions[model_name] = clust_pred

In [85]:
model_name = 'Random'

X = df.drop(['sector'], axis=1).values
dict_features[model_name] = X

clust_pred = np.random.choice(df_predictions['original_n'].unique(), size=len(df))
df_predictions[model_name] = clust_pred

# Calculating metrics

In [12]:
from sklearn.metrics import (davies_bouldin_score, 
                            silhouette_score,
                            calinski_harabasz_score,
                            homogeneity_score)



metrics = {'silhouette':silhouette_score, 
           'davies_bouldin':davies_bouldin_score, 
           'calinski_harabasz':calinski_harabasz_score, 
           'homogeneity':homogeneity_score}


metrics_df = pd.DataFrame(columns = list(metrics.keys()))



for model in dict_features.keys():
    metrics_list = []
    for metric_name, metric_formula in metrics.items():
        if metric_name == 'homogeneity':
            metric_meaning = metric_formula(df_predictions['original_n'], df_predictions[model])
        else:
            metric_meaning = metric_formula(dict_features[model], df_predictions[model])
        metrics_list.append(metric_meaning)
    metrics_df.loc[model] = metrics_list
    
metrics_df

NameError: name 'dict_features' is not defined

In [87]:
def rank_methods(df):
    
    for c in df.columns:
        if c == 'davies_bouldin':
            df[c] = df[c].rank(method='dense',ascending=True).astype(int)
        else:
            df[c] = df[c].rank(method='dense',ascending=False).astype(int)
            
    return df.mean(axis=1)

def choose_method(df_mean_ranked):
    method = df_mean_ranked.argmin()
    return method

df_mean_ranked = rank_methods(metrics_df.copy()) 
metrics_df['sum_ranks'] = df_mean_ranked
method = choose_method(df_sum_ranked)
print('best_method: '+ df_ranked.index[method])

metrics_df

best_method: Kmeans_original

,silhouette,davies_bouldin,calinski_harabasz,homogeneity,sum_ranks
Kmeans_original,0.017380,2.878425,18.539991,0.375254,1.25
Random,-0.034273,10.099331,0.942491,0.058006,3.00
Original,-0.014835,3.730855,9.909445,1.000000,1.75

# Saving results

In [13]:
metrics_df.to_csv(config['metrics_path'])
df_predictions.to_csv(config['predictions_path'])